'use strict';
const main=document.querySelector('#content'), banner=document.querySelector('#connection');
const view=location.pathname==='/system'?'system':location.pathname==='/game'?'game':'touch';
document.body.classList.add(view);
document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.pathname==='/'+view));
const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
const number=(n,suffix='',digits=0)=>typeof n==='number'&&Number.isFinite(n)?n.toFixed(digits)+suffix:'Unknown';
const age=t=>t?Math.max(0,Math.floor(Date.now()/1000-t)):'unknown';
const duration=n=>typeof n==='number'&&Number.isFinite(n)?n<60?Math.floor(n)+'s':n<3600?Math.floor(n/60)+'m':(n/3600).toFixed(1)+'h':'Unknown';
function card(grid,title,value,note,wide=false){const c=el('section',undefined,'card'+(wide?' wide':''));c.append(el('h2',title),el('div',value,'value'));if(note)c.append(el('div',note,'sub'));grid.append(c);return c;}
function listCard(grid,title,items){const c=card(grid,title,'','',true),list=el('ul',undefined,'list');c.querySelector('.value').remove();for(const item of items){const li=el('li',item.title||item.text,item.severity);if(item.detail)li.append(el('small',item.detail));if(item.at)li.append(el('small',new Date(item.at*1000).toLocaleTimeString()));list.append(li);}if(!items.length)list.append(el('li','Nothing recorded yet','muted'));c.append(list);return c;}
function chart(c,history,key,color,max){const canvas=el('canvas');canvas.width=800;canvas.height=150;canvas.setAttribute('aria-label',key+' trend over the last ten minutes');c.append(canvas);const ctx=canvas.getContext('2d');ctx.strokeStyle=color;ctx.lineWidth=3;ctx.beginPath();let started=false;history.forEach((p,i)=>{const n=p[key];if(typeof n!=='number'){started=false;return;}const x=i/Math.max(history.length-1,1)*800,y=145-Math.min(n/max,1)*135;if(started)ctx.lineTo(x,y);else ctx.moveTo(x,y);started=true;});ctx.stroke();}
function render(d){main.replaceChildren();const grid=el('div',undefined,'grid');main.append(grid);const stale=age(d.sampled_at)>20||!d.sampled_at,rconStale=age(d.rcon_at)>20||!d.rcon_at;const svc=d.service||{},h=d.host||{},g=d.game||{},m=d.maintenance||{},hist=d.history||[];
 const ready=!stale&&svc.ActiveState==='active'&&!rconStale&&d.game_query_ready===true;let status=ready?'Ready':svc.ActiveState==='active'?'Starting / telemetry unavailable':svc.ActiveState||'Unknown';
 banner.className=stale||rconStale?'stale':'';banner.textContent=stale?'TELEMETRY STALE — displayed values may be old':rconStale?'RCON unavailable — player values may be old; inspect startup if this persists':'LIVE · Local telemetry · Updated every 5 seconds';
 document.querySelector('#sample-age').textContent='Sample age: '+age(d.sampled_at)+'s';
 if(view!=='system')card(grid,'Rust',status,ready?'Game query and local RCON respond':'No automatic restart is requested');
 if(view!=='system')card(grid,'Connected players',rconStale?'Unknown':String((g.players||[]).length),'Restricted deployments: up to four approved players');
 if(view==='game'){const c=card(grid,'Server FPS',number(g.fps),'Last ten minutes');chart(c,hist,'fps','#90e4b5',60);card(grid,'Entities',number(g.entities),'Reported by Rust');}
 if(view==='touch'){card(grid,'Pi temperature',number(h.temperature,'°C',1),h.throttled===null?'Power/throttle telemetry unavailable':'Throttle flags: '+(h.throttled??0).toString(16));card(grid,'USB free',number(h.disk_free_gib,' GiB',1),'Maintain at least 5 GiB update headroom');card(grid,'Last backup',m.backup?.backup_success?duration(age(m.backup.backup_success))+' ago':'Not recorded','Successful backup evidence, not timer enablement');card(grid,'Needs attention',String((d.suggestions||[]).length),d.suggestions?.[0]?.title||'No current suggestions');return;}
 if(view==='game'){const c=card(grid,'Connected players','','',true);c.querySelector('.value').remove();const table=el('table'),head=el('tr');['Player','Ping','Connected'].forEach(t=>head.append(el('th',t)));table.append(head);for(const p of g.players||[]){const row=el('tr');[p.name,number(p.ping,' ms'),duration(p.connected_seconds==null?null:Number(p.connected_seconds))].forEach(t=>row.append(el('td',t)));table.append(row);}c.append(table);if(!g.players?.length)c.append(el('p',rconStale?'Player list unavailable':'No players connected','muted'));listCard(grid,'Join / leave activity',d.events||[]);card(grid,'Game uptime',duration(g.uptime_seconds),'Reported by Rust');card(grid,'Rust+ listener',d.companion_listener?'Listening':'Not listening','Local TCP check only; external pairing is not verified');card(grid,'Last observed save',m.journal?.last_save?duration(age(m.journal.last_save))+' ago':'Unknown','From the bounded maintenance journal check');return;}
 const cpu=(h.cpu||[]).reduce((a,b)=>a+b,0)/Math.max(h.cpu?.length||0,1);chart(card(grid,'CPU',number(cpu,'%'),(h.cpu||[]).map((v,i)=>'Core '+i+': '+v+'%').join(' · ')),hist,'cpu','#90e4b5',100);
 chart(card(grid,'Memory',number(h.memory_percent,'%'),number(h.memory_used_gib,' GiB',1)+' / '+number(h.memory_total_gib,' GiB',1)+' · Swap '+number(h.swap_used_mib,' MiB')),hist,'memory','#8dbaf7',100);
 card(grid,'Temperature',number(h.temperature,'°C',1),'Current throttle bitmask: '+(h.throttled===null?'unknown':h.throttled));card(grid,'USB free',number(h.disk_free_gib,' GiB',1),number(h.disk_percent,'% used')+' · Host disk R/W '+number(h.read_kib_s,'/',0)+number(h.write_kib_s,' KiB/s',0));
 const packages=m.packages||{},rust=m.rust||{};card(grid,'Package updates',packages.ok?String(packages.count):'Unknown',(packages.security_count??'?')+' security · checked '+duration(age(packages.checked_at))+' ago · Reboot '+(m.reboot_required?'requested':'not signalled'));card(grid,'Rust build',rust.installed||'Unknown','Available '+(rust.available||'?')+' · '+(rust.ok?'checked '+duration(age(rust.checked_at))+' ago':'check failed/not run'));
 card(grid,'FEX release',m.fex?.latest_release||'Unknown','Installed '+(m.fex?.installed_pin||'?')+' · manual compatibility review');card(grid,'Backup age',m.backup?.backup_success?duration(age(m.backup.backup_success)):'Not recorded','Verify restore on a spare system');
 listCard(grid,'Needs attention',d.suggestions||[]);listCard(grid,'Operational checks',[{title:'Network receive/send: '+number(h.rx_kib_s,' / ',1)+number(h.tx_kib_s,' KiB/s',1),detail:'Wi-Fi '+number(h.wifi_dbm,' dBm')},{title:'Automatic Rust restarts: '+(svc.NRestarts??'?'),detail:'Cumulative systemd counter'},{title:'Journal warning matches: '+(m.journal?.warning_matches??'?'),detail:m.journal?.scope||'No successful journal check'},{title:'Ansible result: not tracked',detail:'Review the most recent controller or AWX job; no success is inferred.'}]);
}
async function refresh(){document.querySelector('#clock').textContent=new Date().toLocaleTimeString();try{const response=await fetch('/api/status',{cache:'no-store'});if(!response.ok)throw Error();render(await response.json());}catch{banner.className='stale';banner.textContent='DASHBOARD DISCONNECTED — values below are stale';}setTimeout(refresh,5000);}refresh();
