---
- name: Run one or all RustberryPi maintenance jobs
  hosts: rust_servers
  become: true
  serial: 1
  roles:
    - role: rust_nas
      when: rust_nas_enabled | default(false) | bool
    - rust_maintenance
